document.addEventListener('DOMContentLoaded', function () {
    var button = document.getElementById('randomButton');
    var sentenceText = document.getElementById('sentenceText');

    button.addEventListener('click', function () {
        var sentences = [
            "no pressure but pressure",
            "how status?",
            "nieustające pasmo sukcesów",
            "czuję pewien niepokój",
            "jestem umiarkowanym optymistą",
            "mam głębokie przeczucie",
            "it's nice to be important but it's more important to be nice",
            "youtuber",
            "szanowni",
            "nothing fancy",
            "which is fine",
            "Taaak, bardzo dobre pytanie",
            "co na demo",
            "Guys [pauza]",
            "Taki dobry żart, że aż HRy chcą go usłyszeć",
            "Prośba o wycenę",
            "Bo!...",
            "nie chcę nic mówić, ale…",
            "tego",
            "which is fine",
            "it's an issue",
            "no elo",
            "najs",
            "pięknego dnia Wam życzę",
            "to robi sens",
            "A B C - always be closing",
            "tnijmy scope",
            "enabler sukcesu",
            "mocno zajęty",
            "od ludzi z XXX mamy zielone światło",
            "jesteśmy w pasie startowym",
            "mam eskalować?",
            "czyli możemy tego taska na done już zmienić?",
            "będę zobowiązany",
            "zobacz na listę zależności",
            "w ogólności natomiast",
            "wyznaczysz ochotnika?",
            "proste",
            "jakoś martwi mnie",
            "patrz, jaką apkę zrobiłem w weekend",
            "zapytam nieśmiało",
            "jak do labradora",
            "be on the same page",
            "Moment, moment / chwila, chwila",
            "Dajcie szansę",
            "to nie jego pierwsze rodeo",
            "generalnie...",
            "to co, suchar? Jest bardzo zły, ja wiem",
            "wixa przy golfie",
            "byłbym super wdzięczny",
            "Będę miał prośbę",
            "tableau wybuchło",
            "heurystykę potrzebuje",
            "musimy zajrzeć pod każdy kamień",
            "zostałem wywłaszczony",
            "Natomiast mam tyle srok, że już każdej za ogon nie trzymam",
            "Dzięki Panowie",
            "Macie jakieś silne przekonania?",
            "klawo",
            "To konkluduje to spotkanie",
            "pyku cyku",
            "tak trzeba żyć"
        ];


        var randomIndex = Math.floor(Math.random() * sentences.length);
        sentenceText.textContent = sentences[randomIndex];
    });
});
